version: "2"         # required to adjust maintainability checks
checks:
  identical-code:
    config:
      threshold: 50 # language-specific defaults. an override will affect all languages.
  method-complexity:
    config:
      threshold: 6
